name: Build for WEB and Android

on:
  push:
    branches:
      - master

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - Android # Build an Android .apk standalone app.
    steps:
      - name: Get repository name
        id: repo-name
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          echo "Repository name: $REPO_NAME"
          echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@v1.3.1
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.repo-name.outputs.repo_name }}-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
      
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ steps.repo-name.outputs.repo_name }}-${{ matrix.targetPlatform }}
          path: artifacts

      - name: Extract APK from ZIP
        run: |
          mkdir -p builds/${{ matrix.targetPlatform }}
          unzip -j artifacts/*.zip -d builds/${{ matrix.targetPlatform }}

      - name: Update README.md with APK download link
        run: |
          APK_FILE=$(ls builds/${{ matrix.targetPlatform }}/*.apk)
          APK_NAME=$(basename $APK_FILE)
          DOWNLOAD_URL="https://github.com/${{ github.repository }}/releases/latest/download/$APK_NAME"
          # Перезаписываем 14 строку README.md
          sed -i "14s/.*/${{ matrix.targetPlatform }} : [Download $APK_NAME]($DOWNLOAD_URL)/" README.md
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update README.md with APK download link for ${{ matrix.targetPlatform }}"
          git push

      - name: Upload APK to builds folder
        uses: actions/upload-artifact@v3
        with:
          name: apk-builds
          path: builds/${{ matrix.targetPlatform }}