name: Build for WEB and Android

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
          uses: actions/setup-java@v1
          with:
            java-version: '11' # Указываем версию JDK для сборки Android

      - name: Set up Unity License
          uses: game-ci/unity-request-activation-file@v2
          with:
            unityVersion: 2023.3.11f1 # Укажите вашу версию Unity
            projectPath: . # Путь к вашему проекту Unity

      - name: Cache Unity Library
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Build WebGL
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: WebGL
          projectPath: .
          buildMethod: BuildScript.BuildWebGL # Укажите ваш метод сборки для WebGL

      - name: Build Android
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: Android
          projectPath: .
          buildMethod: BuildScript.BuildAndroid # Укажите ваш метод сборки для Android

      - name: Upload WebGL Build
        uses: actions/upload-artifact@v2
        with:
          name: WebGL-Build
          path: build/WebGL

      - name: Upload Android Build
        uses: actions/upload-artifact@v2
        with:
          name: Android-Build
          path: build/Android